[platformio]
default_envs = front

[env]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200

[env:front]
build_src_filter =
    +<front_controller.cpp>

lib_deps =
    marcoschwartz/LiquidCrystal_I2C
    chris--a/Keypad
    https://github.com/joeyoung/arduino_keypads.git

[env:motor]
build_src_filter =
    +<motor_controller.cpp>

lib_deps =
    waspinator/AccelStepper